using Application.Features.Cars.Commands.Create;
using Application.Features.Cars.Commands.Delete;
using Application.Features.Cars.Commands.Update;
using Application.Features.Cars.Queries.GetById;
using Application.Features.Cars.Queries.GetList;
using AutoMapper;
using NArchitecture.Core.Application.Responses;
using Domain.Entities;
using NArchitecture.Core.Persistence.Paging;
using Application.Features.CarModels.Queries.GetDynamic;
using Application.Features.Cars.Queries.GetDynamic;

namespace Application.Features.Cars.Profiles;

public class MappingProfiles : Profile
{
    public MappingProfiles()
    {
        CreateMap<CreateCarCommand, Car>();
        CreateMap<Car, CreatedCarResponse>();

        CreateMap<UpdateCarCommand, Car>();
        CreateMap<Car, UpdatedCarResponse>();

        CreateMap<DeleteCarCommand, Car>();
        CreateMap<Car, DeletedCarResponse>();

        CreateMap<Car, GetByIdCarResponse>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.ChassisNumber, opt => opt.MapFrom(src => src.ChassisNumber))
            .ForMember(dest => dest.Plate, opt => opt.MapFrom(src => src.Plate))
            .ForMember(dest => dest.Kilometers, opt => opt.MapFrom(src => src.Kilometers))
            .ForMember(dest => dest.SpareKey, opt => opt.MapFrom(src => src.SpareKey))
            .ForMember(dest => dest.Inquiry, opt => opt.MapFrom(src => src.Inquiry))
            .ForMember(dest => dest.WheelType, opt => opt.MapFrom(src => src.WheelType))
            .ForMember(dest => dest.SpareWheel, opt => opt.MapFrom(src => src.SpareWheel))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Price))
            .ForMember(dest => dest.BrandId, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Id))
            .ForMember(dest => dest.BrandName, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Name))
            .ForMember(dest => dest.BrandLogo, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Logo))
            .ForMember(dest => dest.GenerationId, opt => opt.MapFrom(src => src.ModalExtension.Generation.Id))
            .ForMember(dest => dest.GenerationName, opt => opt.MapFrom(src => src.ModalExtension.Generation.Name))
            .ForMember(dest => dest.ModalExtensionId, opt => opt.MapFrom(src => src.ModalExtension.Id))
            .ForMember(dest => dest.ModalExtensionName, opt => opt.MapFrom(src => src.ModalExtension.Name))
            .ForMember(dest => dest.ModalExtensionLenght, opt => opt.MapFrom(src => src.ModalExtension.Lenght))
            .ForMember(dest => dest.ModalExtensionWidth, opt => opt.MapFrom(src => src.ModalExtension.Width))
            .ForMember(dest => dest.ModalExtensionHeight, opt => opt.MapFrom(src => src.ModalExtension.Height))
            .ForMember(dest => dest.ModalExtensionFuelTank, opt => opt.MapFrom(src => src.ModalExtension.FuelTank))
            .ForMember(dest => dest.ModalExtensionLuggageCapacity, opt => opt.MapFrom(src => src.ModalExtension.LuggageCapacity))
            .ForMember(dest => dest.ModalExtensionEmptyWeight, opt => opt.MapFrom(src => src.ModalExtension.EmptyWeight))
            .ForMember(dest => dest.ModalExtensionModelYear, opt => opt.MapFrom(src => src.ModalExtension.ModelYear))
            .ForMember(dest => dest.CarModelId, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Id))
            .ForMember(dest => dest.CarModelName, opt => opt.MapFrom(src => src.ModalExtension.CarModel.ModelName))
            .ForMember(dest => dest.ColorId, opt => opt.MapFrom(src => src.Color.Id))
            .ForMember(dest => dest.ColorName, opt => opt.MapFrom(src => src.Color.Name))
            .ForMember(dest => dest.EngineId, opt => opt.MapFrom(src => src.Engine.Id))
            .ForMember(dest => dest.EngineNo, opt => opt.MapFrom(src => src.Engine.EngineNo))
            .ForMember(dest => dest.EngineCapacity, opt => opt.MapFrom(src => src.Engine.EngineCapacity))
            .ForMember(dest => dest.EngineMotorPower, opt => opt.MapFrom(src => src.Engine.MotorPower))
            .ForMember(dest => dest.EngineMaximumTorque, opt => opt.MapFrom(src => src.Engine.MaximumTorque))
            .ForMember(dest => dest.EngineAcceleration, opt => opt.MapFrom(src => src.Engine.Acceleration))
            .ForMember(dest => dest.EngineMaximumSpeed, opt => opt.MapFrom(src => src.Engine.MaximumSpeed))
            .ForMember(dest => dest.EngineFuelTankVolume, opt => opt.MapFrom(src => src.Engine.FuelTankVolume))
            .ForMember(dest => dest.EngineOutOfTownConsumptionRate, opt => opt.MapFrom(src => src.Engine.OutOfTownConsumptionRate))
            .ForMember(dest => dest.EngineUrbanConsumptionRate, opt => opt.MapFrom(src => src.Engine.UrbanConsumptionRate))
            .ForMember(dest => dest.EngineAverageConsumptionRate, opt => opt.MapFrom(src => src.Engine.AverageConsumptionRate))
            .ForMember(dest => dest.FuelTypeId, opt => opt.MapFrom(src => src.Engine.FuelType.Id))
            .ForMember(dest => dest.FuelTypeName, opt => opt.MapFrom(src => src.Engine.FuelType.Name))
            .ForMember(dest => dest.BodyTypeId, opt => opt.MapFrom(src => src.BodyType.Id))
            .ForMember(dest => dest.BodyTypeBodyName, opt => opt.MapFrom(src => src.BodyType.BodyName))
            .ForMember(dest => dest.BodyTypeDoor, opt => opt.MapFrom(src => src.BodyType.Door))
            .ForMember(dest => dest.TransmissionId, opt => opt.MapFrom(src => src.Transmission.Id))
            .ForMember(dest => dest.TransmissionName, opt => opt.MapFrom(src => src.Transmission.Name))
            .ForMember(dest => dest.ExpertizeResultId, opt => opt.MapFrom(src => src.ExpertizeResult.Id))
            .ForMember(dest => dest.ExpertizeResultCarDamageInformationRecord, opt => opt.MapFrom(src => src.ExpertizeResult.CarDamageInformationRecord))
            .ForMember(dest => dest.ExpertizeResultInquiryDate, opt => opt.MapFrom(src => src.ExpertizeResult.InquiryDate))
            .ForMember(dest => dest.ExpertizeResultChassisPartId, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.Id))
            .ForMember(dest => dest.ExpertizeResultBodyShellPartId, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Id))
            .ForMember(dest => dest.ChassisPartIsRightChassisChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsRightChassisChanged))
            .ForMember(dest => dest.ChassisPartIsLeftChassisChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsLeftChassisChanged))
            .ForMember(dest => dest.ChassisPartIsFrontPanelChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsFrontPanelChanged))
            .ForMember(dest => dest.ChassisPartIsBackPanelChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsBackPanelChanged))
            .ForMember(dest => dest.BodyShellPartLeftFrontFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftFrontFender))
            .ForMember(dest => dest.BodyShellPartLeftFrontDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftFrontDoor))
            .ForMember(dest => dest.BodyShellPartLeftRearDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftRearDoor))
            .ForMember(dest => dest.BodyShellPartLeftRearFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftRearFender))
            .ForMember(dest => dest.BodyShellPartRightFrontFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightFrontFender))
            .ForMember(dest => dest.BodyShellPartRightFrontDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightFrontDoor))
            .ForMember(dest => dest.BodyShellPartRightRearDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightRearDoor))
            .ForMember(dest => dest.BodyShellPartRightRearFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightRearFender))
            .ForMember(dest => dest.BodyShellPartFrontbumper, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Frontbumper))
            .ForMember(dest => dest.BodyShellPartRearBumper, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RearBumper))
            .ForMember(dest => dest.BodyShellPartBonnet, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Bonnet))
            .ForMember(dest => dest.BodyShellPartCeiling, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Ceiling))
            .ForMember(dest => dest.BodyShellPartLuggage, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Luggage))
            .ForMember(dest => dest.SellerId, opt => opt.MapFrom(src => src.Seller.Id))
            .ForMember(dest => dest.SellerUserId, opt => opt.MapFrom(src => src.Seller.UserId))
            .ForMember(dest => dest.SellerName, opt => opt.MapFrom(src => src.Seller.Name))
            .ForMember(dest => dest.SellerPhoneNumber, opt => opt.MapFrom(src => src.Seller.PhoneNumber))
            .ForMember(dest => dest.SellerLicenceId, opt => opt.MapFrom(src => src.Seller.Licence.Id))
            .ForMember(dest => dest.SellerLocationId, opt => opt.MapFrom(src => src.Seller.Location.Id))
            .ForMember(dest => dest.LicenceLicenceNo, opt => opt.MapFrom(src => src.Seller.Licence.LicenceNo))
            .ForMember(dest => dest.LicenceProvidedBy, opt => opt.MapFrom(src => src.Seller.Licence.ProvidedBy))
            .ForMember(dest => dest.LocationCity, opt => opt.MapFrom(src => src.Seller.Location.City))
            .ForMember(dest => dest.LocationAddress, opt => opt.MapFrom(src => src.Seller.Location.Address))
            .ForMember(dest => dest.LocationLatitute, opt => opt.MapFrom(src => src.Seller.Location.Latitute))
            .ForMember(dest => dest.LocationLongitute, opt => opt.MapFrom(src => src.Seller.Location.Longitute)); ;

        CreateMap<Car, GetListCarListItemDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.ChassisNumber, opt => opt.MapFrom(src => src.ChassisNumber))
            .ForMember(dest => dest.Plate, opt => opt.MapFrom(src => src.Plate))
            .ForMember(dest => dest.Kilometers, opt => opt.MapFrom(src => src.Kilometers))
            .ForMember(dest => dest.SpareKey, opt => opt.MapFrom(src => src.SpareKey))
            .ForMember(dest => dest.Inquiry, opt => opt.MapFrom(src => src.Inquiry))
            .ForMember(dest => dest.WheelType, opt => opt.MapFrom(src => src.WheelType))
            .ForMember(dest => dest.SpareWheel, opt => opt.MapFrom(src => src.SpareWheel))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Price))
            .ForMember(dest => dest.BrandId, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Id))
            .ForMember(dest => dest.BrandName, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Name))
            .ForMember(dest => dest.BrandLogo, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Logo))
            .ForMember(dest => dest.GenerationId, opt => opt.MapFrom(src => src.ModalExtension.Generation.Id))
            .ForMember(dest => dest.GenerationName, opt => opt.MapFrom(src => src.ModalExtension.Generation.Name))
            .ForMember(dest => dest.ModalExtensionId, opt => opt.MapFrom(src => src.ModalExtension.Id))
            .ForMember(dest => dest.ModalExtensionName, opt => opt.MapFrom(src => src.ModalExtension.Name))
            .ForMember(dest => dest.ModalExtensionLenght, opt => opt.MapFrom(src => src.ModalExtension.Lenght))
            .ForMember(dest => dest.ModalExtensionWidth, opt => opt.MapFrom(src => src.ModalExtension.Width))
            .ForMember(dest => dest.ModalExtensionHeight, opt => opt.MapFrom(src => src.ModalExtension.Height))
            .ForMember(dest => dest.ModalExtensionFuelTank, opt => opt.MapFrom(src => src.ModalExtension.FuelTank))
            .ForMember(dest => dest.ModalExtensionLuggageCapacity, opt => opt.MapFrom(src => src.ModalExtension.LuggageCapacity))
            .ForMember(dest => dest.ModalExtensionEmptyWeight, opt => opt.MapFrom(src => src.ModalExtension.EmptyWeight))
            .ForMember(dest => dest.ModalExtensionModelYear, opt => opt.MapFrom(src => src.ModalExtension.ModelYear))
            .ForMember(dest => dest.CarModelId, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Id))
            .ForMember(dest => dest.CarModelName, opt => opt.MapFrom(src => src.ModalExtension.CarModel.ModelName))
            .ForMember(dest => dest.ColorId, opt => opt.MapFrom(src => src.Color.Id))
            .ForMember(dest => dest.ColorName, opt => opt.MapFrom(src => src.Color.Name))
            .ForMember(dest => dest.EngineId, opt => opt.MapFrom(src => src.Engine.Id))
            .ForMember(dest => dest.EngineNo, opt => opt.MapFrom(src => src.Engine.EngineNo))
            .ForMember(dest => dest.EngineCapacity, opt => opt.MapFrom(src => src.Engine.EngineCapacity))
            .ForMember(dest => dest.EngineMotorPower, opt => opt.MapFrom(src => src.Engine.MotorPower))
            .ForMember(dest => dest.EngineMaximumTorque, opt => opt.MapFrom(src => src.Engine.MaximumTorque))
            .ForMember(dest => dest.EngineAcceleration, opt => opt.MapFrom(src => src.Engine.Acceleration))
            .ForMember(dest => dest.EngineMaximumSpeed, opt => opt.MapFrom(src => src.Engine.MaximumSpeed))
            .ForMember(dest => dest.EngineFuelTankVolume, opt => opt.MapFrom(src => src.Engine.FuelTankVolume))
            .ForMember(dest => dest.EngineOutOfTownConsumptionRate, opt => opt.MapFrom(src => src.Engine.OutOfTownConsumptionRate))
            .ForMember(dest => dest.EngineUrbanConsumptionRate, opt => opt.MapFrom(src => src.Engine.UrbanConsumptionRate))
            .ForMember(dest => dest.EngineAverageConsumptionRate, opt => opt.MapFrom(src => src.Engine.AverageConsumptionRate))
            .ForMember(dest => dest.FuelTypeId, opt => opt.MapFrom(src => src.Engine.FuelType.Id))
            .ForMember(dest => dest.FuelTypeName, opt => opt.MapFrom(src => src.Engine.FuelType.Name))
            .ForMember(dest => dest.BodyTypeId, opt => opt.MapFrom(src => src.BodyType.Id))
            .ForMember(dest => dest.BodyTypeBodyName, opt => opt.MapFrom(src => src.BodyType.BodyName))
            .ForMember(dest => dest.BodyTypeDoor, opt => opt.MapFrom(src => src.BodyType.Door))
            .ForMember(dest => dest.TransmissionId, opt => opt.MapFrom(src => src.Transmission.Id))
            .ForMember(dest => dest.TransmissionName, opt => opt.MapFrom(src => src.Transmission.Name))
            .ForMember(dest => dest.ExpertizeResultId, opt => opt.MapFrom(src => src.ExpertizeResult.Id))
            .ForMember(dest => dest.ExpertizeResultCarDamageInformationRecord, opt => opt.MapFrom(src => src.ExpertizeResult.CarDamageInformationRecord))
            .ForMember(dest => dest.ExpertizeResultInquiryDate, opt => opt.MapFrom(src => src.ExpertizeResult.InquiryDate))
            .ForMember(dest => dest.ExpertizeResultChassisPartId, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.Id))
            .ForMember(dest => dest.ExpertizeResultBodyShellPartId, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Id))
            .ForMember(dest => dest.ChassisPartIsRightChassisChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsRightChassisChanged))
            .ForMember(dest => dest.ChassisPartIsLeftChassisChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsLeftChassisChanged))
            .ForMember(dest => dest.ChassisPartIsFrontPanelChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsFrontPanelChanged))
            .ForMember(dest => dest.ChassisPartIsBackPanelChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsBackPanelChanged))
            .ForMember(dest => dest.BodyShellPartLeftFrontFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftFrontFender))
            .ForMember(dest => dest.BodyShellPartLeftFrontDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftFrontDoor))
            .ForMember(dest => dest.BodyShellPartLeftRearDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftRearDoor))
            .ForMember(dest => dest.BodyShellPartLeftRearFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftRearFender))
            .ForMember(dest => dest.BodyShellPartRightFrontFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightFrontFender))
            .ForMember(dest => dest.BodyShellPartRightFrontDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightFrontDoor))
            .ForMember(dest => dest.BodyShellPartRightRearDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightRearDoor))
            .ForMember(dest => dest.BodyShellPartRightRearFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightRearFender))
            .ForMember(dest => dest.BodyShellPartFrontbumper, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Frontbumper))
            .ForMember(dest => dest.BodyShellPartRearBumper, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RearBumper))
            .ForMember(dest => dest.BodyShellPartBonnet, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Bonnet))
            .ForMember(dest => dest.BodyShellPartCeiling, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Ceiling))
            .ForMember(dest => dest.BodyShellPartLuggage, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Luggage))
            .ForMember(dest => dest.SellerId, opt => opt.MapFrom(src => src.Seller.Id))
            .ForMember(dest => dest.SellerUserId, opt => opt.MapFrom(src => src.Seller.UserId))
            .ForMember(dest => dest.SellerName, opt => opt.MapFrom(src => src.Seller.Name))
            .ForMember(dest => dest.SellerPhoneNumber, opt => opt.MapFrom(src => src.Seller.PhoneNumber))
            .ForMember(dest => dest.SellerLicenceId, opt => opt.MapFrom(src => src.Seller.Licence.Id))
            .ForMember(dest => dest.SellerLocationId, opt => opt.MapFrom(src => src.Seller.Location.Id))
            .ForMember(dest => dest.LicenceLicenceNo, opt => opt.MapFrom(src => src.Seller.Licence.LicenceNo))
            .ForMember(dest => dest.LicenceProvidedBy, opt => opt.MapFrom(src => src.Seller.Licence.ProvidedBy))
            .ForMember(dest => dest.LocationCity, opt => opt.MapFrom(src => src.Seller.Location.City))
            .ForMember(dest => dest.LocationAddress, opt => opt.MapFrom(src => src.Seller.Location.Address))
            .ForMember(dest => dest.LocationLatitute, opt => opt.MapFrom(src => src.Seller.Location.Latitute))
            .ForMember(dest => dest.LocationLongitute, opt => opt.MapFrom(src => src.Seller.Location.Longitute)); ;
        CreateMap<IPaginate<Car>, GetListResponse<GetListCarListItemDto>>();

        CreateMap<Car, GetDynamicCarResponse>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.ChassisNumber, opt => opt.MapFrom(src => src.ChassisNumber))
            .ForMember(dest => dest.Plate, opt => opt.MapFrom(src => src.Plate))
            .ForMember(dest => dest.Kilometers, opt => opt.MapFrom(src => src.Kilometers))
            .ForMember(dest => dest.SpareKey, opt => opt.MapFrom(src => src.SpareKey))
            .ForMember(dest => dest.Inquiry, opt => opt.MapFrom(src => src.Inquiry))
            .ForMember(dest => dest.WheelType, opt => opt.MapFrom(src => src.WheelType))
            .ForMember(dest => dest.SpareWheel, opt => opt.MapFrom(src => src.SpareWheel))
            .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Price))
            .ForMember(dest => dest.BrandId, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Id))
            .ForMember(dest => dest.BrandName, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Name))
            .ForMember(dest => dest.BrandLogo, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Brand.Logo))
            .ForMember(dest => dest.GenerationId, opt => opt.MapFrom(src => src.ModalExtension.Generation.Id))
            .ForMember(dest => dest.GenerationName, opt => opt.MapFrom(src => src.ModalExtension.Generation.Name))
            .ForMember(dest => dest.ModalExtensionId, opt => opt.MapFrom(src => src.ModalExtension.Id))
            .ForMember(dest => dest.ModalExtensionName, opt => opt.MapFrom(src => src.ModalExtension.Name))
            .ForMember(dest => dest.ModalExtensionLenght, opt => opt.MapFrom(src => src.ModalExtension.Lenght))
            .ForMember(dest => dest.ModalExtensionWidth, opt => opt.MapFrom(src => src.ModalExtension.Width))
            .ForMember(dest => dest.ModalExtensionHeight, opt => opt.MapFrom(src => src.ModalExtension.Height))
            .ForMember(dest => dest.ModalExtensionFuelTank, opt => opt.MapFrom(src => src.ModalExtension.FuelTank))
            .ForMember(dest => dest.ModalExtensionLuggageCapacity, opt => opt.MapFrom(src => src.ModalExtension.LuggageCapacity))
            .ForMember(dest => dest.ModalExtensionEmptyWeight, opt => opt.MapFrom(src => src.ModalExtension.EmptyWeight))
            .ForMember(dest => dest.ModalExtensionModelYear, opt => opt.MapFrom(src => src.ModalExtension.ModelYear))
            .ForMember(dest => dest.CarModelId, opt => opt.MapFrom(src => src.ModalExtension.CarModel.Id))
            .ForMember(dest => dest.CarModelName, opt => opt.MapFrom(src => src.ModalExtension.CarModel.ModelName))
            .ForMember(dest => dest.ColorId, opt => opt.MapFrom(src => src.Color.Id))
            .ForMember(dest => dest.ColorName, opt => opt.MapFrom(src => src.Color.Name))
            .ForMember(dest => dest.EngineId, opt => opt.MapFrom(src => src.Engine.Id))
            .ForMember(dest => dest.EngineNo, opt => opt.MapFrom(src => src.Engine.EngineNo))
            .ForMember(dest => dest.EngineCapacity, opt => opt.MapFrom(src => src.Engine.EngineCapacity))
            .ForMember(dest => dest.EngineMotorPower, opt => opt.MapFrom(src => src.Engine.MotorPower))
            .ForMember(dest => dest.EngineMaximumTorque, opt => opt.MapFrom(src => src.Engine.MaximumTorque))
            .ForMember(dest => dest.EngineAcceleration, opt => opt.MapFrom(src => src.Engine.Acceleration))
            .ForMember(dest => dest.EngineMaximumSpeed, opt => opt.MapFrom(src => src.Engine.MaximumSpeed))
            .ForMember(dest => dest.EngineFuelTankVolume, opt => opt.MapFrom(src => src.Engine.FuelTankVolume))
            .ForMember(dest => dest.EngineOutOfTownConsumptionRate, opt => opt.MapFrom(src => src.Engine.OutOfTownConsumptionRate))
            .ForMember(dest => dest.EngineUrbanConsumptionRate, opt => opt.MapFrom(src => src.Engine.UrbanConsumptionRate))
            .ForMember(dest => dest.EngineAverageConsumptionRate, opt => opt.MapFrom(src => src.Engine.AverageConsumptionRate))
            .ForMember(dest => dest.FuelTypeId, opt => opt.MapFrom(src => src.Engine.FuelType.Id))
            .ForMember(dest => dest.FuelTypeName, opt => opt.MapFrom(src => src.Engine.FuelType.Name))
            .ForMember(dest => dest.BodyTypeId, opt => opt.MapFrom(src => src.BodyType.Id))
            .ForMember(dest => dest.BodyTypeBodyName, opt => opt.MapFrom(src => src.BodyType.BodyName))
            .ForMember(dest => dest.BodyTypeDoor, opt => opt.MapFrom(src => src.BodyType.Door))
            .ForMember(dest => dest.TransmissionId, opt => opt.MapFrom(src => src.Transmission.Id))
            .ForMember(dest => dest.TransmissionName, opt => opt.MapFrom(src => src.Transmission.Name))
            .ForMember(dest => dest.ExpertizeResultId, opt => opt.MapFrom(src => src.ExpertizeResult.Id))
            .ForMember(dest => dest.ExpertizeResultCarDamageInformationRecord, opt => opt.MapFrom(src => src.ExpertizeResult.CarDamageInformationRecord))
            .ForMember(dest => dest.ExpertizeResultInquiryDate, opt => opt.MapFrom(src => src.ExpertizeResult.InquiryDate))
            .ForMember(dest => dest.ExpertizeResultChassisPartId, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.Id))
            .ForMember(dest => dest.ExpertizeResultBodyShellPartId, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Id))
            .ForMember(dest => dest.ChassisPartIsRightChassisChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsRightChassisChanged))
            .ForMember(dest => dest.ChassisPartIsLeftChassisChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsLeftChassisChanged))
            .ForMember(dest => dest.ChassisPartIsFrontPanelChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsFrontPanelChanged))
            .ForMember(dest => dest.ChassisPartIsBackPanelChanged, opt => opt.MapFrom(src => src.ExpertizeResult.ChassisPart.IsBackPanelChanged))
            .ForMember(dest => dest.BodyShellPartLeftFrontFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftFrontFender))
            .ForMember(dest => dest.BodyShellPartLeftFrontDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftFrontDoor))
            .ForMember(dest => dest.BodyShellPartLeftRearDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftRearDoor))
            .ForMember(dest => dest.BodyShellPartLeftRearFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.LeftRearFender))
            .ForMember(dest => dest.BodyShellPartRightFrontFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightFrontFender))
            .ForMember(dest => dest.BodyShellPartRightFrontDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightFrontDoor))
            .ForMember(dest => dest.BodyShellPartRightRearDoor, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightRearDoor))
            .ForMember(dest => dest.BodyShellPartRightRearFender, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RightRearFender))
            .ForMember(dest => dest.BodyShellPartFrontbumper, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Frontbumper))
            .ForMember(dest => dest.BodyShellPartRearBumper, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.RearBumper))
            .ForMember(dest => dest.BodyShellPartBonnet, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Bonnet))
            .ForMember(dest => dest.BodyShellPartCeiling, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Ceiling))
            .ForMember(dest => dest.BodyShellPartLuggage, opt => opt.MapFrom(src => src.ExpertizeResult.BodyShellPart.Luggage))
            .ForMember(dest => dest.SellerId, opt => opt.MapFrom(src => src.Seller.Id))
            .ForMember(dest => dest.SellerUserId, opt => opt.MapFrom(src => src.Seller.UserId))
            .ForMember(dest => dest.SellerName, opt => opt.MapFrom(src => src.Seller.Name))
            .ForMember(dest => dest.SellerPhoneNumber, opt => opt.MapFrom(src => src.Seller.PhoneNumber))
            .ForMember(dest => dest.SellerLicenceId, opt => opt.MapFrom(src => src.Seller.Licence.Id))
            .ForMember(dest => dest.SellerLocationId, opt => opt.MapFrom(src => src.Seller.Location.Id))
            .ForMember(dest => dest.LicenceLicenceNo, opt => opt.MapFrom(src => src.Seller.Licence.LicenceNo))
            .ForMember(dest => dest.LicenceProvidedBy, opt => opt.MapFrom(src => src.Seller.Licence.ProvidedBy))
            .ForMember(dest => dest.LocationCity, opt => opt.MapFrom(src => src.Seller.Location.City))
            .ForMember(dest => dest.LocationAddress, opt => opt.MapFrom(src => src.Seller.Location.Address))
            .ForMember(dest => dest.LocationLatitute, opt => opt.MapFrom(src => src.Seller.Location.Latitute))
            .ForMember(dest => dest.LocationLongitute, opt => opt.MapFrom(src => src.Seller.Location.Longitute));

        CreateMap<IPaginate<Car>, GetListResponse<GetDynamicCarResponse>>();
    }
}